// Code generated by "stringer -type Operator_pli -linecomment tokens_pli.go"; DO NOT EDIT.

package syntax

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NEQ1-1]
	_ = x[NEQ2-2]
	_ = x[NEQ3-3]
	_ = x[GE1-4]
	_ = x[GE2-5]
	_ = x[GE3-6]
	_ = x[LE1-7]
	_ = x[LE2-8]
	_ = x[LE3-9]
	_ = x[HANDLEPTR-10]
	_ = x[PTRPTR-11]
	_ = x[POWER-12]
	_ = x[NOT-13]
	_ = x[MOT1-14]
	_ = x[AND-15]
	_ = x[CONCAT-16]
	_ = x[CONCAT1-17]
	_ = x[OR-18]
	_ = x[Lss-19]
	_ = x[Leq-20]
	_ = x[Gtr-21]
	_ = x[Geq-22]
	_ = x[Add-23]
	_ = x[Sub-24]
	_ = x[Mul-25]
	_ = x[Div-26]
	_ = x[Rem-27]
	_ = x[And-28]
	_ = x[Shl-29]
	_ = x[Shr-30]
}

const _Operator_pli_name = "<>^=~=^<~<>=^>~><==>->**^~&||!!|<<=>>=+-*/%&<<>>"

var _Operator_pli_index = [...]uint8{0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 25, 26, 27, 29, 31, 32, 33, 35, 36, 38, 39, 40, 41, 42, 43, 44, 46, 48}

func (i Operator_pli) String() string {
	i -= 1
	if i >= Operator_pli(len(_Operator_pli_index)-1) {
		return "Operator_pli(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Operator_pli_name[_Operator_pli_index[i]:_Operator_pli_index[i+1]]
}
